name: compose

services:
    seq:
        image: datalust/seq
        container_name: mata-atlantica-seq
        environment:
            SEQ_PASSWORD: admin
            ACCEPT_EULA: Y
        volumes:
            - mata-atlantica-v2:/data
        ports:
            - 8080:80
            - 5341:5341

volumes:
    mata-atlantica-v2: