name: Deployment
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
      
      - name: Test with the dotnet CLI
        run: dotnet test --no-build

      - name: Publishing
        run: dotnet publish src/MataAtlanticaV2.Api/MataAtlanticaV2.Api.csproj -c Release -o publish

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/MataAtlanticaV2.Api/Dockerfile
          push: true
          tags: spudin/mata-atlanticav2:${{ steps.extract_branch.outputs.branch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: publish

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment: Dev
    env:
      VALOR: ${{ vars.VALOR }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: artifacts

      - name: list contents
        run: ls