name: Deployment
on: 
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
      
      - name: Test with the dotnet CLI
        run: dotnet test --no-build
  deploy:
    runs-on: ubuntu-latest
    needs: test # Transforma a execucao dos jobs sequencial: test -> deploy
    steps:
      - name: Publishing
        run: dotnet publish -c Release
      
      - name: Deploying
        run: echo 'Deploying ...'
