name: Deployment
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
      
      - name: Test with the dotnet CLI
        run: dotnet test --no-build

      - name: Publishing
        run: dotnet publish src/MataAtlanticaV2.Api/MataAtlanticaV2.Api.csproj -c Release -o publish

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      # --- START: GCP Authentication using Service Account Key ---
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push
        run: gcloud auth configure-docker gcr.io,us.gcr.io,eu.gcr.io, southamerica-east1-docker.pkg.dev
      # --- END: GCP Authentication Steps ---

      - name: Build and push to GCR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/MataAtlanticaV2.Api/Dockerfile
          push: true
          tags: southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mata-atlanticav2/${{ steps.extract_branch.outputs.branch }}:latest

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: publish

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment: Dev
    env:
      VALOR: ${{ vars.VALOR }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: artifacts

      - name: list contents
        run: ls